#!/bin/sh
wget --no-check-certificate -O - -q -t 1 localhost/nosh/backup
if [ -d /vagrant ]; then
	mv /noshdocuments/*.sql /vagrant/
fi
DIR=$(dirname $0)
cd $DIR
wget --no-check-certificate -O - -q -t 1 localhost/nosh/update_system
composer self-update
composer install
